// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8xgXImt-qXxKL-8InzvYzsP0wcTDMrms',
    appId: '1:240536702825:web:09e9270cceba86b280b7f8',
    messagingSenderId: '240536702825',
    projectId: 'handcraftsapp-a1786',
    authDomain: 'handcraftsapp-a1786.firebaseapp.com',
    storageBucket: 'handcraftsapp-a1786.firebasestorage.app',
    measurementId: 'G-280542F7C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMBJYtYSP86fLFlQ9JsDk7sQYgN9ASUgQ',
    appId: '1:240536702825:android:77ed94ef564e2e3d80b7f8',
    messagingSenderId: '240536702825',
    projectId: 'handcraftsapp-a1786',
    storageBucket: 'handcraftsapp-a1786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByTceR7iiLH4WCI5LA29JEZxNMi_Xg2p4',
    appId: '1:240536702825:ios:20003ea41b2faa9480b7f8',
    messagingSenderId: '240536702825',
    projectId: 'handcraftsapp-a1786',
    storageBucket: 'handcraftsapp-a1786.firebasestorage.app',
    iosBundleId: 'com.example.handcraftsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByTceR7iiLH4WCI5LA29JEZxNMi_Xg2p4',
    appId: '1:240536702825:ios:20003ea41b2faa9480b7f8',
    messagingSenderId: '240536702825',
    projectId: 'handcraftsapp-a1786',
    storageBucket: 'handcraftsapp-a1786.firebasestorage.app',
    iosBundleId: 'com.example.handcraftsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8xgXImt-qXxKL-8InzvYzsP0wcTDMrms',
    appId: '1:240536702825:web:d50ace6f376fc23180b7f8',
    messagingSenderId: '240536702825',
    projectId: 'handcraftsapp-a1786',
    authDomain: 'handcraftsapp-a1786.firebaseapp.com',
    storageBucket: 'handcraftsapp-a1786.firebasestorage.app',
    measurementId: 'G-2Y80T0MZMX',
  );
}
